<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_product = $block->getProduct(); ?>
<?php if ($_product->isSaleable()): ?>

<div class="box-tocart">
    <button class="action primary tocart" type="button" onclick="window.location='<?php echo $block->getUrl('customer/account/login') ?>';" title="<?php /* @escapeNotVerified */ echo __('please login') ?>"><?php echo __('please login') ?></button>
</div>

<?php endif; ?>
